#!/usr/bin/env bash
set -Eeuo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

export PICOLLM_STABLE_FLASH_DEFAULT=0
if [[ "${PICOLLM_FLASH_IMPL:-}" == "sdpa" ]]; then
  unset PICOLLM_FLASH_IMPL
fi

export PICOLLM_ENABLE_FP8="${PICOLLM_ENABLE_FP8:-1}"
export PICOLLM_PRETRAIN_ACTIVATION_CHECKPOINTING="${PICOLLM_PRETRAIN_ACTIVATION_CHECKPOINTING:-1}"
export PICOLLM_DEVICE_BATCH_SIZE="${PICOLLM_DEVICE_BATCH_SIZE:-4}"
export PICOLLM_TOTAL_BATCH_SIZE="${PICOLLM_TOTAL_BATCH_SIZE:--1}"
export PICOLLM_TRAIN_LOSS_CHUNK_ROWS="${PICOLLM_TRAIN_LOSS_CHUNK_ROWS:-4}"
export PICOLLM_PRETRAIN_EVAL_MODES="${PICOLLM_PRETRAIN_EVAL_MODES:-sample,core}"
export PICOLLM_PRETRAIN_MAX_PER_TASK="${PICOLLM_PRETRAIN_MAX_PER_TASK:-8}"
export PICOLLM_CHAT_EVAL_MAX_PROBLEMS="${PICOLLM_CHAT_EVAL_MAX_PROBLEMS:-8}"
export PICOLLM_CHAT_EVAL_BATCH_SIZE="${PICOLLM_CHAT_EVAL_BATCH_SIZE:-8}"

exec bash "$SCRIPT_DIR/speedrun.sh" "$@"
